---
output:
  pdf_document: default
  html_document: default
---
# Process Integration

Process integration projects are made in collaboration with industrial partners and researchers from EPFL. The project can be considered as a master thesis in industry (PDMe). For such projects, we propose, as a function of the scope of the project the possible combination of a semester and a master project:

1. ** Semester Project ** : Energy audit of a production plant
The goal is to define the demand and characterise the energy use in an industrial process.
2. ** Master Project ** : Mitigating $CO_2$ emissions of an industrial site.
The goal is to identify the energy savings and energy conversion options to mitigate the $CO_2$ emissions of the industrial site. The study includes the integration of the process in the energy system and the urban system. In the master project, you will use and validate advanced tools for the decision support of $CO_2$ mitigation options for the industry. In this master thesis, you will also investigate how the results can be generalised to show the impact at the level of the energy system of the country.

## Skills
- Interest and understanding of energy systems
- independent and motivated
- Coding skills in Python, Lua, Matlab, AMPL or other are of advantage 
- Lectures: 
   - ME-454 Modelling and Optimisation of Energy systems
   - ME-451 Advanced Energetics
   - ME-409 Energy Conversion and/or Renewable Energy


