---
output:
  pdf_document: default
  html_document: default
---

## Study of high temperature heat pumps and their energy integration to dairy processes for decarbonization purposes

Contact: Daniel Flórez-Orrego, daniel.florezorrego@epfl.ch

Master project in collaboration with ELSA (MIGROS) Estavayer Lait SA

### Objectives
The goal is to study the integration of high temperature heat pumps in the milk production process using Osmose platform and Coolprop package.

### Profile
-Interest in energy systems and energy integration methods.
-knowledge on refrigeration and compression systems.
-Knowledge on R, Python and Lua is desirable.


### Project plan
The study includes:

1. energy audit and interaction with industry
2. hot and cold streams definition and graphical representation
3. energy integration and exergy analysis of the heat recovery processes
4. use of a heat pump superstructure model to identify the opportunities for integration in industrial processes
5. techno-economic and environmental impact of the heat pump system
6. $CO_2$ mitigation options for the industrial processes (e.g. heat pumps for cleaning in place, tixotherm unit, etc.)
6. opportunities for renewable energy integration and fossil fuel replacement

### Observation
The project is also related to the International Energy Agency Annex 58 on High Temperature Heat Pumps, in collaboration with OST, ELSA, CREMO, SPIESS, CSD, OFEN and EPFL.

### Sources
See more at: https://heatpumpingtechnologies.org/annex58/wp-content/uploads/sites/70/2022/03/description-of-swiss-team-for-annex-58.pdf

### Supervisors
Daniel Flórez-Orrego, daniel.florez.orrego@epfl.ch
Eduardo Pina, eduardo.pina@epfl.ch
Francois Maréchal, francois.marechal@epfl.ch
