---
output:
  pdf_document: default
  html_document: default
---

## Study of the decarbonization alternatives in the aluminium production industry (NetZero Lab)

Contact: Daniel Flórez-Orrego, daniel.florezorrego@epfl.ch

Semester/Master project in collaboration with Novelis company

### Objectives
The goal is to determine the decarbonization potential of the aluminium production via integration of different energy conversion processes in a real aluminium plant in Switzerland. The goal is attaining Net Zero by the next decade.

### Profile
- Interest in energy systems and energy integration.
- knowledge on energy conversion in high temperature systems (melters, casting, waste heat recovery).
- Knowledge on R, Python and Lua is desirable.


### Project plan
The study includes:

1. energy audit and interaction with industry
2. hot and cold streams definition and graphical representation
3. energy integration and exergy analysis of the heat recovery processes
4. technology integration study looking to decarbonize the whole industrial processes (fuel cells, PV panels, electrolyzers, electric furnaces, gasification, ORCs, among others)
5. techno-economic and environmental impact of the proposed systems
6. opportunities for renewable energy integration and fossil fuel replacement

### Observation
The project is related to the Net Zero Lab in collaboration with Novelis Sierre and HESSO Valais.

### Sources
See more at: https://www.novelis.com/net-zero-lab-valais/

### Supervisors
Daniel Flórez-Orrego, daniel.florez.orrego@epfl.ch
Francois Maréchal, francois.marechal@epfl.ch
