---
output:
  pdf_document: default
  html_document: default
  word_document: default
---
# Urban Systems

## Boosting Swiss Energy Transition through Energy as a Service business model
*Master Project*

### Context 

The paradigm shift from fossil fuel-fired centralized towards renewable distributed generation, along with the penetration of digital and renewable technologies in the energy sector, and the transformation from consumers to prosumers, has doubtless increased the degree of complexity of the emerging challenges for energy management. Thus, energy providers delivering a more comprehensive energy service (including energy management advice and solutions), is probably the key distinctive element that makes the EaaS a truly innovative (and essential) approach.


### The project

The aim of this project is to understand the potential of the Energy as a Service business model for boosting energy transition for a specific geographical context. The key research questions to be tackled are: 
1. What are the main drivers, trends and barriers affecting the EaaS market deployment?
2. Which financial tools and business models are used and what applications will they bring to market?
3. What are the global perspectives and possible innovations for EaaS?
4. Who are the most appropriate actors that will deploy the EaaS?
5. Does the EaaS represent a true added value for the energy transition?


### Skills
* Interest and understanding of energy systems
* Keen interest in **economic and financial modelling** for energy systems
* Familiarity with smart grids technological solutions
* Programming skills: Python (or similar) would be appreciated
* Other soft skills that are highly appreciated
    * Motivation, autonomy and self-organization
    * Ability to communicate results, especially in written form


### Work structure
* Contributing to literature review for the Energy as a Service: papers + reports + case studies;
* Review of state-of-the-art approaches and definition of a quantitative strategy to analyse the economic performance, financial flows and impact of the technological solution on the society.
* *Not part of this work: Identification of technical solutions (energy system configuration at urban scale, ensuring the energy balance of the territory and complying with the 2050 net-zero carbon emissions targets)*
* From this technical solution that is given and the known associated investments to be made, explore the different financial solutions for the deployment of a same technical solution, and calculate the energy exchange costs for each stakeholder depending on its contribution to the installed capacities.
* Quantification of benefits through ad-hoc KPIs, and performance assessment of the different solutions.


### Location
The IPESE laboratory is located in the EPFL Valais campus. Working in the Sion office or remotely will depend on the Covid situation. In case in Sion, travels between Lausanne and Sion are compensated by EPFL. But regarding master projects, we highly suggest you to look for an apartment in Sion, surrounded by the most beautiful mountains in the world, allowing you to enjoy the medieval town, the market on Fridays and Switzerland’s best wines and beers.

### Supervisors
If interested, please contact Ermanno Lo Cascio (mailto:ermanno.locascsio@epfl.ch) and Dorsan Lepour (mailto:dorsan.lepour@epfl.ch) attaching your CV and a short motivation message.


## Clustering and typification of urban districts for energy systems modelling
*Master Project*

### Context 

The success of the energy transition, in a world with more than two-thirds of human beings living in urban areas, involves the emergence of smart cities. These urban areas hosting millions of residents will be backboned by integrated and coordinated multi-energy systems, offering customized energy solutions and services to each individual. For this purpose, mutualized infrastructures need to be deployed at every stage of the system: from energy harvesting, transport, and storage; to mobility services and goods production. The best suited scope to study the deployment and promotion of these local capacities and shared infrastructures appears to be the district perspective.


### The project

The aim of this study is to define the boundaries of such districts. A definition and assessment of energy hubs (or “clusters”) within urban areas will be constructed in 4 parts:  

* Identification of the residents and industries needs
* Characterization of the territory (endogenous resources and renewables potential)
* Clustering based on differentiating features
* Definition of typical districts
The results will be generated in a GIS database (= Geographical Information System), and the methodology validated on the canton of Geneva.

### Skills
* Interest and understanding of energy systems
* Basic knowledge in machine learning methods (especially clustering and PCA, for the study of differentiating versus non-differentiating features)
* Mastering QGIS (or a similar GIS tool)
* Programming skills in Python


### Location
The IPESE laboratory is located in the EPFL Valais campus. Working in the Sion office or remotely will depend on the Covid situation. In case in Sion, travels between Lausanne and Sion are compensated by EPFL. But regarding master projects, we highly suggest you to look for an apartment in Sion, surrounded by the most beautiful mountains in the world, allowing you to enjoy the medieval town, the market on Fridays and Switzerland’s best wines and beers.

### Supervisor
If interested, please contact Dorsan Lepour (mailto:dorsan.lepour@epfl.ch) attaching your CV and a short motivation message.


## Characterization of technologies for district-scale optimization of multi-energy systems
*Master project / or Semester followed by Master project*

### Context 

The financial and environmental benefits of a district integrated approach for the mutualization of capacities have already been proved (ie, the benefits for communities to share facilities for energy harvesting or energy storage), but their implementation mechanisms need to be further studied. The aim of this project is to determine the required capacities to ensure the energy balance of a territory, and assess the best scale for their deployment: building-scale versus district-scale. Indeed, a compromise between full decentralization (every building has its own capacities and is energy-autarkic) and full centralization (all units are installed at district-level) has to be determined. This optimal level for the mutualization of capacities will be found by minimizing the total costs to be supported by the community (investments + operating costs).

### The project

The project will be structured in following parts:

* Definition of specific costs for technologies at building-scale versus district-scale
* Development of a MILP model for optimal energy system design
* Assessment of energy solutions based on mutualized capacities
* Results generation and scenarios exploration
* Discussion and report writing

### Skills
* Good ease in literature review and data collection
* Good understanding of energy systems
* Programming skills in AMPL and Python
* Mastering GIS tools is a plus
* Courses:
  * ME-454 Modelling and Optimization of Energy systems
  * ME-409 Energy Conversion or Renewable Energy


### Location
The IPESE laboratory is located in the EPFL Valais campus. Working in the Sion office or remotely will depend on the Covid situation. In case in Sion, travels between Lausanne and Sion are compensated by EPFL. But regarding master projects, we highly suggest you to look for an apartment in Sion, surrounded by the most beautiful mountains in the world, allowing you to enjoy the medieval town, the market on Fridays and Switzerland’s best wines and beers.

### Supervisor
If interested, please contact Dorsan Lepour (mailto:dorsan.lepour@epfl.ch) attaching your CV and a short motivation message.


## Development of a GIS database for analysis and visualization of energy scenarios
*Semester project*

### Context

The aim of the project is to illustrate the integration of an energy solution into the territory and for its residents. Starting from a technical solution of an energy system (design and operation of capacities are known), the financial solution linking all stakeholders and system infrastructure needs to be superimposed, to get a combined visualization of monetary flows alongside energy flows.

### The project

The project will be structured in following parts:  

* Development of an interactive map using a GIS platform
* Combined visualization of a solution from a technical and financial perspective
  * Energy flows: installed capacities and operation
  * Monetary flows: investments and tariffs for energy exchanges
* Comparison of solutions through KPIs (= key performance indicators) and standardized metrics (2000W society, energy consumption in `W*y/y`, specific needs for buildings in `.../m2`, specific needs for people in `.../capita`)

### Skills
* Good understanding of energy systems (Sankey diagrams)
* Mastering QGIS tools
* Programming skills in Python (we will probably use the [pyam library](https://pyam-iamc.readthedocs.io/en/stable/))

### Location
The IPESE laboratory is located in the EPFL Valais campus. Working in the Sion office or remotely will depend on the Covid situation. In case in Sion, travels between Lausanne and Sion are compensated by EPFL.

### Supervisor
If interested, please contact Dorsan Lepour (mailto:dorsan.lepour@epfl.ch) attaching your CV and a short motivation message.
