---
output:
  pdf_document: default
  html_document: default
---
# Process Efficiency

## Closing the Balance - industrial processes as an actor in the energy system of the future
*Semester project*

### Context 

In this project, the potential of  biomass-based process industries integrated in the energy system to serve as decentralized energy storage hubs is evaluated. 

Respecting the production demands of the industrial sector, the treatment of biogenic  streams in consideration of the fluctuations in the  national energy system will be analyzed. For the integration, both the material (carbon) as well as the enrgetic properties of resources will be considered. Appart from fuel and syngas production form biogenic resiudals and electricity, fuel cell systems and carbon capture and utilization units will be included as optional processes. The defined process superstructure that consists of the industrial prcess and the options on how to valorize its residual streams will be used for solution generation for different energy system profiles (scenarios). 
The generated solutions will provide insights on the potetial of the bio-based industrial sector to contribute storage opportunitiesa and avoid fossil emissions on a national level. 

The detialed process models are already available for the most part, although they might be adapted slightly.  The modeling focus of this project is thus more on the system side, so on the definition of the scenarios considering demand and price profiles as well as the definition of appropriate time series aggregation strategies. 

### The project

The project consists of multiple steps: 

- Literature review: get an overview of the current state, formulate research question
- Data aquisition: for example supply and demand profiles, market prices
- Model implementation: adapt existing process models for your project
- Scenario definition: use quired data to define scenarios
- Result generation, interpretation and report writing 

Motivated and skilled students will have the opportunity conslidate their research into a scientific paper, for this, they will be hired at IPESE as a student researcher for up to 6 months after the thesis submission. 

### Skills
- Interest and understanding of energy systems
- independent and motivated
- Coding skills in Python, Lua, Matlab, AMPL or other are of advantage 
- Lectures: 
   - ME-454 Modelling and Optimisation of Energy systems
   - Energy Conversion and/or Renewable Energy


### Location
The project will be held in Sion. 

### Supervisor
In case of interest, please send your CV and a short motivation letter including your experience/knowledge in the field to Julia Granacher. 
mailto:julia.granacher@epfl.ch


## Integration of steam distribution network with storage and power recovery
*Master project*

### Context 
An industrial utility supplier, in France, produces and transfers utilities, especially steam, to the nearby industrial plants. Due to the current site configuration, sometimes steam is in excess, and so it is vented into environment. 

In order to improve the energy efficiency of utility supplier, there is a strong need of heat/steam storage. Further, any extra heat has to be valorized into mechanical power / electricity. The steam is supplied to the industrial partners at different pressure levels, with varying daily demands. This project aims to develop heat/steam storage models, and integrate them with steam distributions network and steam cycle, to improve the overall performance of the utility system.  

### The project
This project will be organised in the following steps. 

- Analysis and understanding of the research problem.
- Development of steam distribution network for industrial site.
- Development of energy storage models. 
- Integration of steam distribution network, energy storage, and steam cycle.  

### Skills
- Experience with flowsheeting software.
- Understanding of thermodynamic cycles, energy integration and process optimization.
- Results interpretation and report writing.
- Coding skills: R, AMPL.
- Lectures: Modelling and Optimisation of Energy systems, Energy Conversion and/or Renewable Energy.

### Administrative 
This project is a part of collaborative research work between IPESE/EPFL and Terega (France). The project will be supervised by Shivom (IPESE/EPFL) and Myriam (TEREGA, France). If interested, please send your CV, with short motivation letter, to Shivom/Myriam. 

### Location
This research work will be conducted at IPESE/EPFL, Sion. Student will discuss his/her work with collaborators in Terega, in bi-weekly video meetings. 

### Supervisors
Dr. Shivom Sharma, mailto: shivom.sharma@epfl.ch  
Dr. Myriam Etancelin, mailto: myriam.etancelin@terega.fr

