---
output:
  pdf_document: default
  html_document: default
---
# Demonstrator CO2 capture

In the scope of Scientastic, EPFL-Valais opens its doors to the general public. In that regard, IPESE is developing a direct air capture (DAC) machine. The goal is to harvest CO2 from air and produce sparkling water.

Currently we are looking for TWO students:

1. **Chemistry/Chemical engineer**
As air passes through the adsorbent bed, CO2 needs to be retained. Due to its use for a beverage, CO2 needs to be of high-purity. For that we are recruiting a student from chemistry or chemical engineering to functionalize silica beads. Due to previous experience, the lab of prof. Wendy agreed on supervising the procedure in partnership with HES-SO.
Therefore the ideal student is/has:

- highly motivated in the topic

- background in lab work is a plus

- collaborative spirit to develop an interdisciplinary project

2. **Mechanical/Chemical/Industrial Engineer**
The student at this level (from HES-SO or EPFL) needs to design the mechanical engineering project in collaboration with the ‘atelier mechanic’ of EPFL. In particular, the computer-aided design (CAD) needs to ensure adequate air compression and operation to be able to harvest the necessary amount of air for a bottle of 0.75L. This constitutes a challenge and a trade-off that needs simulation.
Therefore the ideal student is/has:

- highly motivated in the topic

- background in using design software

- goal-oriented and hands-on approach attitude

- collaborative spirit to develop an interdisciplinary project

Interested students should send an application attaching CV, transcript of records (bachelor and master) and a motivation letter to rafael.amoedo@epfl.ch. Applications are reviewed on a chronological order and the positions remain open until suitable candidates are found.
