--- 
title: "Student Projects"
author: "IPESE"
date: "`r Sys.Date()`"
output: pdf_document
documentclass: book
bibliography:
- book.bib
- packages.bib
description: |
  This side summarises all necessary information regarding student project proposals at IPESE
link-citations: yes
github-repo: rstudio/bookdown-demo
site: bookdown::bookdown_site
---



# Students projects
The IPESE group is proposing an integrated concept of teaching where semester/master projects and lectures are considered as a whole entity.

The undergraduate studies for the mechanical engineering master combine lectures and projects. Thus it is recommended that the students realizing a project in our lab also register to the lectures given by Prof. Maréchal.

The lab is now located in the new campus of EPFL in Sion .

Students will be reimbursed for the travel to Sion.

You will find all necessary details together with contact information on the respective project page.

Students interested in doing a semester or master project in IPESE and who have not found a specific project of interest in the list of available projects can send a CV together with a motivation letter and a transcript of records (Bachelor, Master) to [StudentProjectsIPESE](StudentProjectsIPESE@groupes.epfl.ch). Your chances of finding an appropriate supervisor increase, when directly contacting a person from the IPESE lab. Therefore, visit the research pages to find your supervisor.

IPESE is also involved in the Minor in Energy: realize your master in 2 years with a special focus on energy and obtain the engineering master + a minor in Energy.

Students are welcomed at IPESE for semester projects, minor in energy projects and master projects. It is strongly recommended to select the projects with some continuity and consistency, selecting for example semester projects that concern different aspects of the same technology and that prepare the master thesis.

The subjects cover different aspects on the fields of research of the IPESE group as can also be seen by the completed projects.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')

```
